"use client";

import { DashboardShell } from "@/components/dashboard-shell";
import { useState } from "react";

export default function SettingsPage() {
  const [saved, setSaved] = useState(false);
  return <DashboardShell><div className="space-y-6"><div><div className="text-[10px] uppercase tracking-[0.2em] text-slate-400">Workspace configuration</div><h1 className="mt-2 text-3xl font-bold tracking-tight text-slate-900">Settings</h1><p className="mt-3 text-sm text-slate-600">Manage project connections, reporting preferences, and team defaults.</p></div><div className="grid gap-6 lg:grid-cols-[1.2fr_0.8fr]"><div className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-sm shadow-slate-200/50"><h2 className="text-xl font-bold text-slate-900">Workspace details</h2><div className="mt-5 space-y-4"><label className="block text-sm font-medium text-slate-700">Workspace name<input defaultValue="Northstar Commerce" className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 font-normal outline-none focus:border-blue-300 focus:bg-white" /></label><label className="block text-sm font-medium text-slate-700">Primary domain<input defaultValue="northstar.com" className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 font-normal outline-none focus:border-blue-300 focus:bg-white" /></label><label className="block text-sm font-medium text-slate-700">Default country<select className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 font-normal outline-none focus:border-blue-300 focus:bg-white"><option>United States</option><option>United Kingdom</option><option>Germany</option></select></label><button onClick={() => { setSaved(true); setTimeout(() => setSaved(false), 2200); }} className="rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-medium text-white hover:bg-slate-800">Save changes</button>{saved ? <span className="ml-3 text-sm text-emerald-600">Changes saved</span> : null}</div></div><div className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-sm shadow-slate-200/50"><h2 className="text-xl font-bold text-slate-900">Connected sources</h2><div className="mt-5 space-y-3">{['Google Search Console', 'Google Analytics 4', 'Sitemap crawler', 'Slack notifications'].map((source, index) => <div key={source} className="flex items-center justify-between rounded-2xl border border-slate-200 bg-slate-50 p-4"><div><div className="text-sm font-semibold text-slate-900">{source}</div><div className="mt-1 text-xs text-slate-500">{index < 3 ? 'Connected and syncing' : 'Not connected'}</div></div><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${index < 3 ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-200 text-slate-600'}`}>{index < 3 ? 'Active' : 'Connect'}</span></div>)}</div></div></div></div></DashboardShell>;
}
